id: P001776
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017316
  title: ཇ་ཡི་བསྟན་བཅོས
  author: ''
  volumes:
    35f065f1180d492a9d9ebc1bd27709a7:
      image_group_id: I00EGS1017318
      title: ''
      volume_number: 1
      total_pages: 140
